[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "PyZALO"
version = "0.1.0"
authors = [
    {name = "PhongVeChai", email = "aimabtdcdungko@gmail.com"},
]
description = "Python library for Zalo OA Bot"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
keywords = ["zalo", "bot", "oa", "chatbot"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "requests>=2.28.0",
    "websocket-client>=1.4.0",
]

[project.urls]
Homepage = "https://github.com/PhongNguyenxDEV/PyZALO"
Issues = "https://github.com/PhongNguyenxDEV/PyZALO/issues"
Documents = "https://bot.zaloplatforms.com/docs/"

[tool.hatch.build.targets.wheel]
packages = ["pyzalo"]